# Generated by Django 2.1 on 2020-04-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=100)),
                ('contact', models.CharField(max_length=12)),
                ('company', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=15)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
